In [2]:
# numpy 사용하기
import numpy as np

In [3]:
data1=[1, 2, 3, 4, 5]
print(data1)
print(type(data1))

[1, 2, 3, 4, 5]
<class 'list'>


In [19]:
data2 = [1, 2, 3, 3.5, 4]
data2

[1, 2, 3, 3.5, 4]

In [6]:
# numpy를 이용하기 위해 array 정의하기

# 1. 위에서 만든 python list를 이용

arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [15]:
# array의 자료형을 확인할 수 있다.

arr2 = np.array(data2)
print(arr2.dtype)
print(arr1.dtype)

float64
int32


In [20]:
arr3 = np.array(data2)
arr3


array([1. , 2. , 3. , 3.5, 4. ])

In [21]:
arr3.shape

(5,)

In [24]:
# 2차원 배열 생성
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr4.shape

(4, 3)

<h3>numpy shape</h3>

numpy에서는 해당 aray의 크기를 알 수 있다.
shape을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.<br>
위에서 arr1.shape의 결과는 (5,)로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.<br>
arr4.shape의 결과는 (4,3)으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array이다.<br>

<h3>numpy 자료형</h3>

arr1이나 arr2는 int64라는 자료형을 갖는 것에 반해 arr3은 float64라는 자료형을 갖는다.<br>
이는 arr3내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.<br>
numpy에서 사용되는 자료형은 아래와 같다.

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8, 16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불린 bool
- 문자열 string_
- 오브젝트 object
- 유니코드 unicode

<h2>2-1. np.zeros(), np.ones, np.arange() 함수</h2>

numpy에서 array를 정의할 때 사용되는 함수들이다.
아래 실습을 통해 각각이 어떻게 다른지 살펴보자.

In [27]:
# np.zeros() : 인자로 받는 크기 만큼, 모든 요소가 0인 array를 만든다. 

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
# 2차원 행렬 생성
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# np.ones() : 인자로 받는 크기 만큼, 모든 요소가 1인 array를 만든다

np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
# 2차원 행렬 생성

np.ones((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
# np.arrange() : 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자의 값-1 이 생성되고 입력한 인자의 값 만큼의 크기를 가진다.

# np.arange(a, b, c) : a ~ b-1까지 c 간격으로
# np.arange(a, b) : a ~ b-1까지 1 간격으로
# np.arange(a) : 0 ~ a-1까지

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [39]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

<h2>3. Array 연산 </h2>

기본적으로 numpy에서 연산을 할 때 크기가 서로 동일한 array끼리 연산이 진행되며
이때 같은 위치에 있는 요소들 끼리 연산이 진행된다.

In [3]:
arr1 = np.array([[1, 2 ,3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr1.shape

(2, 3)

In [45]:
arr2 = np.array([[10, 11, 12], [13, 14 ,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [46]:
arr2.shape

(2, 3)

In [49]:
# list일 경우 
print(type(data1), type(data2))

print(data1 + data2)

<class 'list'> <class 'list'>
[1, 2, 3, 4, 5, 1, 2, 3, 3.5, 4]


## 3-1. array 덧셈

In [50]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [51]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

## 3-3. array 곱셈
 
 같은 위치의 요소끼리 곱한다.

In [52]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

## 3-4. array 나눗셈

마찬가지로 같은 위치의 요소로 나눈다.

In [56]:
print(arr1 / arr2)
print()
print(arr1 % arr2)

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]

[[1 2 3]
 [4 5 6]]


## 3-5 array의 브로드캐스트

위에서 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만, numpy에서는 브로드캐스트라는 기능을 제공한다.<br>
브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게 하는 것이다.

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr1.shape

(2, 3)

In [7]:
arr3 = np.array([10, 11, 12])
arr3

array([10, 11, 12])

In [61]:
arr3.shape

(3,)

In [8]:
# 행 끼리 연산하며 열의 개수는 같아야한다.

arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [64]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다.<br>
연산 결과를 살펴보면 arr3이 [10, 11, 12] 에서 [[10, 11, 12], [10, 11, 12]]로 확장되어 계산되었음을 확인할 수 있다.<br>
동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [66]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [67]:
# 요소에 대해 제곱처리

arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## 4. Array 인덱싱

numpy에서 사용되는 인덱싱은 기본적으로 ptyhon의 list의 인덱싱과 동일하다.<br>
이떄, python에서와 같이 1번째로 시작하는 것이 아니라 9번째로 시작하는 것에 주의하자.<br>

In [69]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# 0번째 요소
arr1[0]

0

In [74]:
# 3번째 요소
arr1[3]

3

In [75]:
# 3 ~ 8 번쨰 요소
arr1[3 : 9]

array([3, 4, 5, 6, 7, 8])

In [76]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2
arr2.shape

(3, 4)

In [80]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 한다.
arr2[0,0]

1

In [81]:
# 2행의 모든 요소 꺼내기
arr2[2, :]

array([ 9, 10, 11, 12])

In [83]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

## 5. Array boolean 인덱싱(마스크)

위에서 이용한 다차원의 인덱싱을 응용하여 boolea 인덱싱을 할 수 있다.<br>
해당 기능은 두로 마스크라고 이야기하는데, boolean 인덱싱을 통해 만들어낸 array를 통해 우리가 원하는 행 또는 열의 값만 뽑아 낼 수 있다.<br>
즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [84]:
names = np.array(["Beone", "Beone", "Kim", "Jain", "Lee", "Beone", "Park", "Beone"])
names

array(['Beone', 'Beone', 'Kim', 'Jain', 'Lee', 'Beone', 'Park', 'Beone'],
      dtype='<U5')

In [85]:
names.shape

(8,)

In [114]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 기우시안 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0 ~ 1 난수를 발생시키는 np.random.rnad() 함수도 존재한다.

data = np.random.randn(8, 4)
data
# np.mean(data)

array([[-0.10977854,  0.16996471,  0.6468282 ,  1.47167685],
       [-0.09873998, -0.18453351,  0.67811954, -0.70117531],
       [ 1.46199275,  0.62945151,  0.10695515,  0.12304283],
       [ 1.09935444,  0.47632718,  1.34152593,  1.51873757],
       [ 1.11499741, -1.40881308, -0.30115072, -0.20418537],
       [-1.21518816, -0.99901348, -1.04798554,  0.3415326 ],
       [-1.80024541, -1.44084224, -0.3601684 ,  0.44708215],
       [-0.9587427 , -0.47977107, -0.54848586,  0.57157731]])

위와 같은 names와 data라는 array가 있다.<br>
이때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.<br>
그리고 이때, names가 Beome인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용한다.

In [89]:
# 요소가 Beone인 항목에 대한 mask 생성
names_Beone_mask = (names == "Beone")
names_Beone_mask

array([ True,  True, False, False, False,  True, False,  True])

In [105]:
# True인 것들만 가져오기(행만 가져옴, 0, 1, 5, 7 행)
# 요소가 Beone인 것에 대한 boolean 값을 가지는 mask를 만들었고 마스크 인덱싱을 이용해 data의 0, 1, 5, 7행을 꺼냈다.
data[names_Beone_mask, :]

array([[-2.09509059,  1.16173166, -0.8410699 ,  0.46556527],
       [ 0.23309271, -0.39556709, -2.07824141, -0.60024168],
       [-0.0246403 , -1.06541153, -2.37312492, -0.36099102],
       [ 0.42993146,  0.52531298,  0.82737663,  0.8050486 ]])

In [116]:
#  요소가 Kim인 행의 테이터만 꺼내기
data[names == "Kim",:]

array([[1.46199275, 0.62945151, 0.10695515, 0.12304283]])

In [119]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == "Kim") | (names == "Park"), :]

array([[ 1.46199275,  0.62945151,  0.10695515,  0.12304283],
       [-1.80024541, -1.44084224, -0.3601684 ,  0.44708215]])

물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.<br>
data array에서 0번째 열의 값이 0보다 작은 행을 구해보자.

In [123]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열 중에 0보다 작은 요소의 boolaen 값은 다음과 같다.
print(data[:, 0] < 0)
print(type(data[:, 0] < 0))

[ True  True False False False  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
# 위에서 만든 마스크를 이용하여 0번째 열들의 값이 0보다 작은 행을 구한다.

In [124]:
data[data[:, 0] < 0, :]

array([[-0.10977854,  0.16996471,  0.6468282 ,  1.47167685],
       [-0.09873998, -0.18453351,  0.67811954, -0.70117531],
       [-1.21518816, -0.99901348, -1.04798554,  0.3415326 ],
       [-1.80024541, -1.44084224, -0.3601684 ,  0.44708215],
       [-0.9587427 , -0.47977107, -0.54848586,  0.57157731]])

이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.<br>
위에서 얻은, 0번째 열의 값이 0보다 작은 해의 2, 3 번째 열값에 0을 대입해보자.

In [125]:
# 0번째 열의 값이 0보다 작은 행의 2, 3번째 열 값
data[data[:, 0] < 0, 2:4]

array([[ 0.6468282 ,  1.47167685],
       [ 0.67811954, -0.70117531],
       [-1.04798554,  0.3415326 ],
       [-0.3601684 ,  0.44708215],
       [-0.54848586,  0.57157731]])

In [127]:
# 0 대입하기
data[data[:, 0] < 0, 2:4] = 0
data

array([[-0.10977854,  0.16996471,  0.        ,  0.        ],
       [-0.09873998, -0.18453351,  0.        ,  0.        ],
       [ 1.46199275,  0.62945151,  0.10695515,  0.12304283],
       [ 1.09935444,  0.47632718,  1.34152593,  1.51873757],
       [ 1.11499741, -1.40881308, -0.30115072, -0.20418537],
       [-1.21518816, -0.99901348,  0.        ,  0.        ],
       [-1.80024541, -1.44084224,  0.        ,  0.        ],
       [-0.9587427 , -0.47977107,  0.        ,  0.        ]])

## 6. Numpy 함수

numpy에서는 array에 적용되는 다양한 함수가 있다.

## 6-1. 하나의 array에 적용되는 함수

In [134]:
arr1 = np.random.randn(5, 3)
print(arr1)
print()

# normal(loc, scale, size) / 평균, 편차, 사이즈
arr2 = np.random.normal(0, 1, (5, 3))
print(arr2)

[[-1.5915456   0.83025223  0.87083262]
 [-0.79594218  1.13041366 -0.58687832]
 [-0.64756419 -0.47508964 -0.56205639]
 [-0.49433066 -0.35180414 -2.37478035]
 [-0.15498931 -0.97071065  1.2305151 ]]

[[ 0.1809027  -1.47288709 -0.79726678]
 [ 1.38351764 -0.34360348  1.34976916]
 [ 0.9710307   1.0208694   1.58584994]
 [ 1.82969813  1.25593837  1.45113324]
 [-0.79981691 -0.14354332 -0.40824508]]


In [135]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[1.5915456 , 0.83025223, 0.87083262],
       [0.79594218, 1.13041366, 0.58687832],
       [0.64756419, 0.47508964, 0.56205639],
       [0.49433066, 0.35180414, 2.37478035],
       [0.15498931, 0.97071065, 1.2305151 ]])

In [136]:
# 각 성분의 제곱근 계산하기( == array ** 0.5), 음수일 경우 null(허수이기 때문)
np.sqrt(arr1)

<ipython-input-136-4215060b9be2>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[       nan, 0.91118178, 0.93318413],
       [       nan, 1.06320913,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan, 1.10928585]])

In [139]:
# 각 성분의 제곱 계산하기
print(np.square(arr1))
print()
print(arr1 ** 2)

[[2.53301739 0.68931877 0.75834946]
 [0.63352395 1.27783505 0.34442617]
 [0.41933938 0.22571017 0.31590738]
 [0.2443628  0.12376615 5.63958173]
 [0.02402169 0.94227916 1.51416741]]

[[2.53301739 0.68931877 0.75834946]
 [0.63352395 1.27783505 0.34442617]
 [0.41933938 0.22571017 0.31590738]
 [0.2443628  0.12376615 5.63958173]
 [0.02402169 0.94227916 1.51416741]]


In [140]:
# 각 성분을 무리수 e의 지수로 삼은 값 계산하기(익스퍼낸셜)
np.exp(arr1)

array([[0.20361067, 2.29389726, 2.38889908],
       [0.45115596, 3.09693733, 0.55606042],
       [0.52331893, 0.62182931, 0.57003564],
       [0.60997905, 0.70341788, 0.09303492],
       [0.85642434, 0.37881374, 3.42299226]])

In [141]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기(음수는 null)
# 자연로그
np.log(arr1)

<ipython-input-141-bddc4320f0c3>:2: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[        nan, -0.18602573, -0.13830549],
       [        nan,  0.12258364,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,  0.20743286]])

In [142]:
# 상용로그
np.log10(arr1)

<ipython-input-142-1d9686adbff8>:2: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1)


array([[        nan, -0.08078995, -0.06006531],
       [        nan,  0.0532374 ,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,  0.09008695]])

In [143]:
# 밑이 2
np.log2(arr1)

<ipython-input-143-3d3b7fd7a7e7>:2: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1)


array([[        nan, -0.2683784 , -0.19953264],
       [        nan,  0.17685081,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,  0.29926236]])

In [144]:
#각 성분의 부호 계산하기(+ = 1, - = -1, 0 = 0)
np.sign(arr1)

array([[-1.,  1.,  1.],
       [-1.,  1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1.,  1.]])

In [145]:
# 각 성분의 소수 첫번째 자리에서 올림한 값 계산
np.ceil(arr1)

array([[-1.,  1.,  1.],
       [-0.,  2., -0.],
       [-0., -0., -0.],
       [-0., -0., -2.],
       [-0., -0.,  2.]])

In [146]:
# 각 성분의 소수 첫번째 자리에서 내림한 값 계산
np.floor(arr1)

array([[-2.,  0.,  0.],
       [-1.,  1., -1.],
       [-1., -1., -1.],
       [-1., -1., -3.],
       [-1., -1.,  1.]])

In [148]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False 반환
np.isnan(np.log10(arr1))

<ipython-input-148-cbec034f80a3>:2: RuntimeWarning: invalid value encountered in log10
  np.isnan(np.log10(arr1))


array([[ True, False, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [150]:
# 각 성분이 무한대인 경우 True, 아닌 경우 Faluse 반환
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# 각 성분에 대해 삼각함수 계산하기
#(cos, cosh, sin, sinh, tan, tanh)

In [151]:
# cos
np.cos(arr1)

array([[-0.02074778,  0.67468961,  0.64418993],
       [ 0.69961187,  0.42628565,  0.83267341],
       [ 0.79755556,  0.88925172,  0.84616099],
       [ 0.88028647,  0.93875255, -0.72012609],
       [ 0.98801318,  0.56471319,  0.33375221]])

In [152]:
# tanh
np.tanh(arr1)

array([[-0.92038597,  0.68061142,  0.70179692],
       [-0.66176211,  0.81116079, -0.52764675],
       [-0.57002791, -0.44230246, -0.50950159],
       [-0.45764685, -0.33797458, -0.98283756],
       [-0.15376008, -0.74901641,  0.84272867]])

## 6-2. 두 개의 array에 적용되는 함수

In [153]:
arr1

array([[-1.5915456 ,  0.83025223,  0.87083262],
       [-0.79594218,  1.13041366, -0.58687832],
       [-0.64756419, -0.47508964, -0.56205639],
       [-0.49433066, -0.35180414, -2.37478035],
       [-0.15498931, -0.97071065,  1.2305151 ]])

In [154]:
arr2 = np.random.randn(5, 3)
arr2

array([[-0.44588557, -1.82439753, -0.92340503],
       [ 0.55509073,  0.28541853, -0.43006098],
       [-1.25092242, -1.20262172,  0.52177735],
       [-0.09439255, -0.35771503, -1.06818107],
       [-0.70365893,  0.01447041,  0.18907634]])

In [159]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산한 값을 계산하기
# (add, subtract, multiply, divide)
np.multiply(arr1, arr2) # == arr1 * arr2
np.add(arr1, arr2) # == arr1 + arr2
np.subtract(arr1, arr2) # == arr1 - arr2
np.divide(arr1, arr2) # == arr1 / arr2

array([[  3.5694037 ,  -0.45508296,  -0.9430668 ],
       [ -1.43389565,   3.96054753,   1.36463979],
       [  0.51766934,   0.39504495,  -1.07719584],
       [  5.2369669 ,   0.98347597,   2.22320018],
       [  0.22026198, -67.08247413,   6.5080331 ]])

In [160]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)
np.maximum(arr1, arr2)

array([[-0.44588557,  0.83025223,  0.87083262],
       [ 0.55509073,  1.13041366, -0.43006098],
       [-0.64756419, -0.47508964,  0.52177735],
       [-0.09439255, -0.35180414, -1.06818107],
       [-0.15498931,  0.01447041,  1.2305151 ]])

## 6-3. 통계 함수

통계 함수를 통해 array의 합이나 평균 등을 구할 때,<br>
추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균 등을 구할 수 있다.

In [161]:
arr1

array([[-1.5915456 ,  0.83025223,  0.87083262],
       [-0.79594218,  1.13041366, -0.58687832],
       [-0.64756419, -0.47508964, -0.56205639],
       [-0.49433066, -0.35180414, -2.37478035],
       [-0.15498931, -0.97071065,  1.2305151 ]])

In [162]:
# 전체 성분의 합을 계산
np.sum(arr1)

-4.943677804326331

In [168]:
# 열 간의 합을 계산
np.sum(arr1, axis=0)

array([-3.68437193,  0.16306147, -1.42236734])

In [164]:
# 전체 성분의 평균을 계산
np.mean(arr1)

-0.32957852028842205

In [9]:
aaa = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [10]:
# 행 간의 평균을 계산
np.mean(aaa, axis=1)

array([1., 2., 3.])

In [166]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)

In [169]:
# 표준편차
np.std(arr1)

0.9680315638933659

In [170]:
np.min(arr1, axis=1)

array([-1.5915456 , -0.79594218, -0.64756419, -2.37478035, -0.97071065])

In [171]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr1)

11

In [173]:
np.argmax(arr1)

14

In [174]:
np.argmax(arr1, axis=0)

array([4, 1, 4], dtype=int64)

In [175]:
# 맨 처음 성분부터 가 성분까지의 누적합 또는 누적곱을 계산(cumsum, cumprod)
np.cumsum(arr1)

array([-1.5915456 , -0.76129336,  0.10953926, -0.68640292,  0.44401074,
       -0.14286758, -0.79043177, -1.26552141, -1.8275778 , -2.32190846,
       -2.6737126 , -5.04849295, -5.20348226, -6.1741929 , -4.9436778 ])

In [176]:
np.cumprod(arr1)

array([-1.5915456 , -1.32138429, -1.15070454,  0.91589428,  1.03533941,
       -0.60761826,  0.39347182, -0.18693439,  0.10506767, -0.05193817,
        0.01827206, -0.04339214,  0.00672532, -0.00652834, -0.00803322])

## 6-4. 기타 함수



In [177]:
arr1

array([[-1.5915456 ,  0.83025223,  0.87083262],
       [-0.79594218,  1.13041366, -0.58687832],
       [-0.64756419, -0.47508964, -0.56205639],
       [-0.49433066, -0.35180414, -2.37478035],
       [-0.15498931, -0.97071065,  1.2305151 ]])

In [178]:
# 전체 성분에 대해서 오름차순으로 정렬
np.sort(arr1)

array([[-1.5915456 ,  0.83025223,  0.87083262],
       [-0.79594218, -0.58687832,  1.13041366],
       [-0.64756419, -0.56205639, -0.47508964],
       [-2.37478035, -0.49433066, -0.35180414],
       [-0.97071065, -0.15498931,  1.2305151 ]])

In [179]:
# 전체 성분에 대해서 내림차순으로 정렬
np.sort(arr1)[::-1]

array([[-0.97071065, -0.15498931,  1.2305151 ],
       [-2.37478035, -0.49433066, -0.35180414],
       [-0.64756419, -0.56205639, -0.47508964],
       [-0.79594218, -0.58687832,  1.13041366],
       [-1.5915456 ,  0.83025223,  0.87083262]])

In [12]:
# 행 반향으로 오름차순으로 정렬(axis = 1(행) / axis = 0(열))
np.sort(arr1, axis=1)

array([[1, 2, 3],
       [4, 5, 6]])