In [1]:
# SVM

import numpy as np
from sklearn.svm import SVC

X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])



In [3]:
# model 만들기
clf = SVC()


# 학습하기
clf.fit(X, y)



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [4]:
# 검증하기
clf.predict(X)



array([1, 1, 2, 2])

## iris data셋을 가져와서
1. train / test를 나누고
2. 학습 / 검증해서 몇프로 맞췄는지 해보기

In [16]:
# iris 데이터셋 가져오기
from sklearn.datasets import load_iris

iris = load_iris()

data = iris.data

target = iris.target

print(data.size)
print(target.size)
print(data)
print()
print(target)

600
150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [11]:
# train_test_split 이용해서 케이스 나누기
from sklearn.model_selection import train_test_split

# train_test_split(입력, 정답, 나눌 비율)
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.33)

In [29]:
print(X_train.size)
print(X_test.size)
print(y_train.size)
print(y_test.size)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

400
200
100
50
(100, 4)
(50, 4)
(100,)
(50,)


In [26]:
# SVM 사용
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [21]:
# model 만들기
clf = SVC()


# 학습하기
clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [24]:
y_predict = clf.predict(X_test)
print(y_predict)

[0 0 0 2 1 0 0 1 0 0 1 1 2 1 0 1 0 1 0 1 2 2 2 1 1 0 0 0 1 1 2 0 2 0 1 1 0
 0 2 0 0 0 2 2 0 0 0 2 2 2]


In [27]:
print(accuracy_score(y_test, y_predict))

1.0


# SVM 파라미터들
class sklearn.svm.SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=- 1, decision_function_shape='ovr', break_ties=False, random_state=None)


C : slack variable<br>
kernal : 가우시안(rbf), ...<br>
degree : <br>
gamma : kernal의 형태(<br>
decision_function_shape

# 흐름

### 데이터 나누기
- from sklearn.model_selection import train_test_split을 이용해<br>
X_train, X_test, y_trin, y_test를 나눈다.<br> 나눌 때는 train_test_split(입력, 정답, 나눌 비율, 랜던 시드 등등)

### 모델
- from sklearn.svm import SVC, from sklearn.tree import DecisionTreeClassifier 처럼 사용할 모듈 불러오기<br>
model = SVC() <br>
model = DecisionTreeClassifier() 처럼 모델 선언

### 학습
- model.fit(입력(train), 정답(train))<br>

### 검증
- model.predict(입력(test))<br>
- y_predict = model.predict(입력(test))으로 검증한 값 저장하기<br>

### 데이터 성능(확률) 확인하기
- from sklearn.metrics import accuracy_score <br>
accuracy_score(정답(test), 검증한 값(y_predict)) 을 이용해 결과를 확인한다.
