In [2]:
from tensorflow.keras import models, layers
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_iris


In [3]:
# iris
# multi, output : 0, 1, 2

iris_data = load_iris()

X = iris_data.data
y = iris_data.target

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=1/3)

In [35]:
print(iris_data.feature_names)
print(iris_data.target_names)
print(iris_data.DESCR)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high

In [33]:
import pandas as pd
df = pd.DataFrame(X, columns = iris_data.feature_names)
df["target"] = y

# units의 수
print(len(df["target"].unique()))

# input_shape의 수
print(len(iris_data.feature_names))

df

3
4


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
# softmax

model = models.Sequential()

model.add(layers.Dense(units = 3, activation="softmax", input_shape=(4,)))
#model.add(layers.Dropout(0.5)) # 드롭아웃 : 오버피팅 막는법
model.compile(optimizer="adam",
             loss = "sparse_categorical_crossentropy",
             metrics = ["acc"])

model.fit(X_train,y_train,epochs = 1000, batch_size = 1, verbose = 1)

Epoch 1/1000
100/100 [==============================] - 0s 780us/step - loss: 1.3968 - acc: 0.7000
Epoch 2/1000
100/100 [==============================] - 0s 835us/step - loss: 0.9886 - acc: 0.7000
Epoch 3/1000
100/100 [==============================] - 0s 700us/step - loss: 0.7408 - acc: 0.7100
Epoch 4/1000
100/100 [==============================] - 0s 740us/step - loss: 0.6562 - acc: 0.7000
Epoch 5/1000
100/100 [==============================] - 0s 810us/step - loss: 0.6400 - acc: 0.6700
Epoch 6/1000
100/100 [==============================] - 0s 880us/step - loss: 0.6140 - acc: 0.6000
Epoch 7/1000
100/100 [==============================] - 0s 970us/step - loss: 0.6051 - acc: 0.6100
Epoch 8/1000
100/100 [==============================] - 0s 810us/step - loss: 0.5917 - acc: 0.6700
Epoch 9/1000
100/100 [==============================] - 0s 730us/step - loss: 0.5795 - acc: 0.6900
Epoch 10/1000
100/100 [==============================] - 0s 890us/step - loss: 0.5732 - acc: 0.6700
Epoch 11/

100/100 [==============================] - 0s 720us/step - loss: 0.3006 - acc: 0.9600
Epoch 84/1000
100/100 [==============================] - 0s 680us/step - loss: 0.2997 - acc: 0.9600
Epoch 85/1000
100/100 [==============================] - 0s 730us/step - loss: 0.2979 - acc: 0.9700
Epoch 86/1000
100/100 [==============================] - 0s 710us/step - loss: 0.2950 - acc: 0.9600
Epoch 87/1000
100/100 [==============================] - 0s 670us/step - loss: 0.2937 - acc: 0.9600
Epoch 88/1000
100/100 [==============================] - 0s 750us/step - loss: 0.2919 - acc: 0.9500
Epoch 89/1000
100/100 [==============================] - 0s 700us/step - loss: 0.2894 - acc: 0.9500
Epoch 90/1000
100/100 [==============================] - 0s 660us/step - loss: 0.2911 - acc: 0.9700
Epoch 91/1000
100/100 [==============================] - 0s 820us/step - loss: 0.2859 - acc: 0.9600
Epoch 92/1000
100/100 [==============================] - 0s 860us/step - loss: 0.2831 - acc: 0.9600
Epoch 93/1000


100/100 [==============================] - 0s 682us/step - loss: 0.1341 - acc: 0.9900
Epoch 246/1000
100/100 [==============================] - 0s 655us/step - loss: 0.1340 - acc: 0.9800
Epoch 247/1000
100/100 [==============================] - 0s 689us/step - loss: 0.1341 - acc: 0.9800
Epoch 248/1000
100/100 [==============================] - 0s 860us/step - loss: 0.1337 - acc: 0.9900
Epoch 249/1000
100/100 [==============================] - 0s 700us/step - loss: 0.1316 - acc: 0.9900
Epoch 250/1000
100/100 [==============================] - 0s 664us/step - loss: 0.1314 - acc: 0.9900
Epoch 251/1000
100/100 [==============================] - 0s 754us/step - loss: 0.1312 - acc: 0.9900
Epoch 252/1000
100/100 [==============================] - 0s 693us/step - loss: 0.1302 - acc: 0.9900
Epoch 253/1000
100/100 [==============================] - 0s 662us/step - loss: 0.1304 - acc: 0.9800
Epoch 254/1000
100/100 [==============================] - 0s 733us/step - loss: 0.1301 - acc: 0.9900
Epoch

100/100 [==============================] - 0s 690us/step - loss: 0.0829 - acc: 0.9900
Epoch 408/1000
100/100 [==============================] - 0s 600us/step - loss: 0.0829 - acc: 0.9900
Epoch 409/1000
100/100 [==============================] - 0s 680us/step - loss: 0.0824 - acc: 0.9900
Epoch 410/1000
100/100 [==============================] - 0s 710us/step - loss: 0.0826 - acc: 0.9900
Epoch 411/1000
100/100 [==============================] - 0s 680us/step - loss: 0.0828 - acc: 0.9900
Epoch 412/1000
100/100 [==============================] - 0s 660us/step - loss: 0.0827 - acc: 0.9900
Epoch 413/1000
100/100 [==============================] - 0s 720us/step - loss: 0.0826 - acc: 0.9900
Epoch 414/1000
100/100 [==============================] - 0s 700us/step - loss: 0.0822 - acc: 0.9900
Epoch 415/1000
100/100 [==============================] - 0s 670us/step - loss: 0.0815 - acc: 0.9900
Epoch 416/1000
100/100 [==============================] - 0s 660us/step - loss: 0.0814 - acc: 0.9900
Epoch

100/100 [==============================] - 0s 670us/step - loss: 0.0616 - acc: 0.9900
Epoch 569/1000
100/100 [==============================] - 0s 750us/step - loss: 0.0620 - acc: 0.9900
Epoch 570/1000
100/100 [==============================] - 0s 680us/step - loss: 0.0616 - acc: 0.9900
Epoch 571/1000
100/100 [==============================] - 0s 650us/step - loss: 0.0626 - acc: 0.9900
Epoch 572/1000
100/100 [==============================] - 0s 630us/step - loss: 0.0613 - acc: 0.9900
Epoch 573/1000
100/100 [==============================] - 0s 670us/step - loss: 0.0614 - acc: 0.9900
Epoch 574/1000
100/100 [==============================] - 0s 710us/step - loss: 0.0607 - acc: 0.9900
Epoch 575/1000
100/100 [==============================] - 0s 660us/step - loss: 0.0612 - acc: 0.9900
Epoch 576/1000
100/100 [==============================] - 0s 660us/step - loss: 0.0608 - acc: 0.9900
Epoch 577/1000
100/100 [==============================] - 0s 730us/step - loss: 0.0602 - acc: 0.9900
Epoch

100/100 [==============================] - 0s 730us/step - loss: 0.0494 - acc: 0.9900
Epoch 731/1000
100/100 [==============================] - 0s 880us/step - loss: 0.0505 - acc: 0.9900
Epoch 732/1000
100/100 [==============================] - 0s 830us/step - loss: 0.0494 - acc: 0.9900
Epoch 733/1000
100/100 [==============================] - 0s 800us/step - loss: 0.0493 - acc: 0.9900
Epoch 734/1000
100/100 [==============================] - 0s 650us/step - loss: 0.0488 - acc: 0.9900
Epoch 735/1000
100/100 [==============================] - 0s 620us/step - loss: 0.0491 - acc: 0.9900
Epoch 736/1000
100/100 [==============================] - 0s 660us/step - loss: 0.0495 - acc: 0.9900
Epoch 737/1000
100/100 [==============================] - 0s 650us/step - loss: 0.0492 - acc: 0.9900
Epoch 738/1000
100/100 [==============================] - 0s 660us/step - loss: 0.0499 - acc: 0.9900
Epoch 739/1000
100/100 [==============================] - 0s 670us/step - loss: 0.0492 - acc: 0.9900
Epoch

Epoch 891/1000
100/100 [==============================] - 0s 570us/step - loss: 0.0422 - acc: 0.9900
Epoch 892/1000
100/100 [==============================] - 0s 610us/step - loss: 0.0419 - acc: 0.9900
Epoch 893/1000
100/100 [==============================] - 0s 600us/step - loss: 0.0423 - acc: 0.9900
Epoch 894/1000
100/100 [==============================] - 0s 680us/step - loss: 0.0426 - acc: 0.9900
Epoch 895/1000
100/100 [==============================] - 0s 690us/step - loss: 0.0420 - acc: 0.9900
Epoch 896/1000
100/100 [==============================] - 0s 610us/step - loss: 0.0420 - acc: 0.9900
Epoch 897/1000
100/100 [==============================] - 0s 590us/step - loss: 0.0416 - acc: 0.9900
Epoch 898/1000
100/100 [==============================] - 0s 620us/step - loss: 0.0421 - acc: 0.9900
Epoch 899/1000
100/100 [==============================] - 0s 560us/step - loss: 0.0418 - acc: 0.9900
Epoch 900/1000
100/100 [==============================] - 0s 630us/step - loss: 0.0420 - ac

100/100 [==============================] - 0s 613us/step - loss: 0.0397 - acc: 0.9900
Epoch 973/1000
100/100 [==============================] - 0s 672us/step - loss: 0.0401 - acc: 0.9900
Epoch 974/1000
100/100 [==============================] - 0s 692us/step - loss: 0.0394 - acc: 0.9900
Epoch 975/1000
100/100 [==============================] - 0s 703us/step - loss: 0.0393 - acc: 0.9900
Epoch 976/1000
100/100 [==============================] - 0s 744us/step - loss: 0.0394 - acc: 1.0000
Epoch 977/1000
100/100 [==============================] - 0s 790us/step - loss: 0.0390 - acc: 0.9900
Epoch 978/1000
100/100 [==============================] - 0s 760us/step - loss: 0.0399 - acc: 0.9900
Epoch 979/1000
100/100 [==============================] - 0s 760us/step - loss: 0.0389 - acc: 0.9900
Epoch 980/1000
100/100 [==============================] - 0s 790us/step - loss: 0.0388 - acc: 0.9900
Epoch 981/1000
100/100 [==============================] - 0s 680us/step - loss: 0.0391 - acc: 0.9900
Epoch

In [12]:
# Test 하는 법

XTest_loss, XTest_acc = model.evaluate(X_test, y_test) # 원래 test 데이터가 들어가야 된다.

print(XTest_acc)

2/2 [==============================] - 0s 1ms/step - loss: 0.1290 - acc: 0.9200
0.9200000166893005


In [17]:
Ttest = model.predict(X_test)
                
print(Ttest)


[[1.52357711e-06 9.93230581e-01 6.76788762e-03]
 [1.00000000e+00 2.51599808e-09 6.77282884e-21]
 [4.49682148e-13 4.38809954e-02 9.56119061e-01]
 [2.84978773e-13 1.55214161e-01 8.44785810e-01]
 [3.70819606e-08 9.25031245e-01 7.49687403e-02]
 [5.14210001e-07 9.81182754e-01 1.88168194e-02]
 [8.59992386e-19 1.30852277e-03 9.98691499e-01]
 [4.00556322e-17 3.34215147e-04 9.99665737e-01]
 [8.81437927e-08 9.87856507e-01 1.21434042e-02]
 [9.99999285e-01 7.35604942e-07 1.03612412e-16]
 [1.52201501e-10 5.15425980e-01 4.84574020e-01]
 [1.84529476e-08 8.07199121e-01 1.92800835e-01]
 [1.33609234e-07 9.54277515e-01 4.57224175e-02]
 [1.46958610e-06 9.91785407e-01 8.21325928e-03]
 [3.09079456e-10 5.98219395e-01 4.01780635e-01]
 [4.97473038e-16 6.80723134e-03 9.93192732e-01]
 [4.67400241e-05 9.97728407e-01 2.22486607e-03]
 [9.99977589e-01 2.23741790e-05 8.91551305e-14]
 [1.07223095e-13 3.25692296e-02 9.67430830e-01]
 [1.50607138e-06 9.88230705e-01 1.17677450e-02]
 [4.52014728e-12 8.07700157e-02 9.192299

In [15]:
# 행 중에 가장 큰 애를 가져온다.
# 이를 y_test와 비교하면 된다!
np.argmax(Ttest, axis = 1)

array([1, 0, 2, 2, 1, 1, 2, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2,
       2, 0, 2, 2, 2, 0, 1, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 1, 0, 1, 0, 2,
       1, 2, 2, 0, 1, 0], dtype=int64)

In [16]:
y_test

array([1, 0, 2, 2, 1, 1, 2, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 2, 1, 2, 1,
       2, 0, 2, 2, 2, 0, 1, 0, 2, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1, 0, 2,
       1, 2, 1, 0, 1, 0])