In [7]:
# wine
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

cancer_data = load_breast_cancer()

X = cancer_data.data
y = cancer_data.target
# X = np.round(cancer_data.data)
# y = np.round(cancer_data.target)

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=1/3)

In [6]:
print(cancer_data.feature_names)
print(cancer_data.target_names)
print(cancer_data.DESCR)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']
.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
 

In [10]:
import pandas as pd
df = pd.DataFrame(X, columns = cancer_data.feature_names)
df["target"] = y

# units의 수
print(len(df["target"].unique()))

# input_shape의 수
print(len(cancer_data.feature_names))

df

2
30


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components=10)

pca.fit(X_train)

cancer_pca_train = pca.transform(X_train) # Train입력
cancer_pca_test = pca.transform(X_test) # Test입력 

In [15]:
# Sigmoid
from tensorflow.keras import models, layers
import numpy as np

model = models.Sequential()

model.add(layers.Dense(units = 256, activation="relu", input_shape=(10,)))
#model.add(layers.Dropout(0.5)) # 드롭아웃 : 오버피팅 막는법
model.add(layers.Dense(units = 128, activation="relu"))

model.add(layers.Dense(units = 64, activation="relu"))

model.add(layers.Dense(units = 32, activation="relu"))

model.add(layers.Dense(units = 1,  activation='sigmoid'))

model.compile(optimizer='adam',
              loss="binary_crossentropy",
              metrics = ['acc'])

model.fit(cancer_pca_train,y_train,epochs = 100, batch_size = 1, verbose = 1)

Epoch 1/100
379/379 [==============================] - 0s 989us/step - loss: 0.5452 - acc: 0.8839
Epoch 2/100
379/379 [==============================] - 0s 871us/step - loss: 0.6095 - acc: 0.9077
Epoch 3/100
379/379 [==============================] - 0s 863us/step - loss: 0.2170 - acc: 0.9340
Epoch 4/100
379/379 [==============================] - 0s 948us/step - loss: 0.2318 - acc: 0.9261
Epoch 5/100
379/379 [==============================] - 0s 963us/step - loss: 0.2072 - acc: 0.9420
Epoch 6/100
379/379 [==============================] - 0s 995us/step - loss: 0.2039 - acc: 0.9367
Epoch 7/100
379/379 [==============================] - 0s 905us/step - loss: 0.2367 - acc: 0.9367
Epoch 8/100
379/379 [==============================] - 0s 797us/step - loss: 0.1576 - acc: 0.9525
Epoch 9/100
379/379 [==============================] - 0s 839us/step - loss: 0.1189 - acc: 0.9551
Epoch 10/100
379/379 [==============================] - 0s 855us/step - loss: 0.1504 - acc: 0.9551
Epoch 11/100
379/37

In [16]:
# Test 하는 법

XTest_loss, XTest_acc = model.evaluate(cancer_pca_test, y_test) # 원래 test 데이터가 들어가야 된다.

print(XTest_acc)

6/6 [==============================] - 0s 1ms/step - loss: 0.1660 - acc: 0.9526
0.9526315927505493


In [17]:
# accuracy는 반올림하나보다
Ttest = model.predict(cancer_pca_test)
                
Ttest

array([[9.6154101e-05],
       [9.9997461e-01],
       [2.0953804e-02],
       [1.0000000e+00],
       [9.9859506e-01],
       [9.9997973e-01],
       [0.0000000e+00],
       [9.9902964e-01],
       [9.9742061e-01],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.7848195e-02],
       [9.8931777e-01],
       [9.9955225e-01],
       [9.9965620e-01],
       [2.4589906e-07],
       [4.2595913e-37],
       [1.0000000e+00],
       [3.8637140e-27],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [8.1126633e-29],
       [2.7591670e-01],
       [9.9980426e-01],
       [9.9832249e-01],
       [2.0539612e-02],
       [9.9977779e-01],
       [5.2342325e-02],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.9996251e-01],
       [2.0068886e-32],
       [1.0000000e+00],
       [9.9903280e-01],
       [0.0000000e+00],
       [9.9994177e-01],
       [7.7251863e-01],
       [0.0000000e+00],
       [9.999971

In [20]:
# 바이너리는 잘 안나오나 보다!!!!!!!!!
np.argmax(Ttest, axis = 1)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [21]:
y_test

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0])