## wine 데이터셋을 이용한 퍼셉트론 구현

1. wine 데이터셋을 로드하시오.

2. 로드한 데이터 셋을 학습용/검증용(train/test)으로 나누시오

3. 학습용 데이터를 PCA를 이용하여 8차원으로 차원 축소를 진행하시오,.

4. 8차원으로 축소된 데이터로 와인을 분류하는 퍼셉트론 알고리즘을 학습을 통해 구현하시오.

5. 검증용 셋으로 검증을 수행하시오.

In [12]:
# wine
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

wine_data = load_wine()

X = wine_data.data
y = wine_data.target


X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=1/3)

In [13]:
from sklearn.decomposition import PCA

pca = PCA(n_components=8)

pca.fit(X_train)

wine_pca_train = pca.transform(X_train) # 얘가 입력 데이터네
wine_pca_test = pca.transform(X_test) # 얘가 입력 데이터네

In [11]:
print(wine_data.feature_names)
print(wine_data.target_names)
print(wine_data.DESCR)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    =========================

In [14]:
import pandas as pd
df = pd.DataFrame(X, columns = wine_data.feature_names)
df["target"] = y

# units의 수
print(len(df["target"].unique()))

# input_shape의 수
print(len(wine_data.feature_names))

df

3
13


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [4]:
from tensorflow.keras import models, layers
import numpy as np


# 여러 레이어를 쌓겠다.
model = models.Sequential()

model.add(layers.Dense(units = 256, activation="relu", input_shape=(8,)))
#model.add(layers.Dropout(0.5)) # 드롭아웃 : 오버피팅 막는법
model.add(layers.Dense(units = 128, activation="relu"))
model.add(layers.Dense(units = 3,  activation='softmax'))



model.compile(optimizer='sgd',
             loss = "sparse_categorical_crossentropy",
             metrics = ['acc'])

model.fit(wine_pca_train, y_train, epochs = 1000, batch_size = 1, verbose = 1)

Epoch 1/1000
118/118 [==============================] - 0s 680us/step - loss: 133.7443 - acc: 0.6610
Epoch 2/1000
118/118 [==============================] - 0s 634us/step - loss: 148.4255 - acc: 0.7203
Epoch 3/1000
118/118 [==============================] - 0s 672us/step - loss: 158.7106 - acc: 0.7034
Epoch 4/1000
118/118 [==============================] - 0s 737us/step - loss: 149.4798 - acc: 0.6949
Epoch 5/1000
118/118 [==============================] - 0s 623us/step - loss: 153.9199 - acc: 0.6780
Epoch 6/1000
118/118 [==============================] - 0s 632us/step - loss: 142.2688 - acc: 0.7288
Epoch 7/1000
118/118 [==============================] - 0s 655us/step - loss: 157.5847 - acc: 0.6695
Epoch 8/1000
118/118 [==============================] - 0s 763us/step - loss: 134.5752 - acc: 0.7373
Epoch 9/1000
118/118 [==============================] - 0s 674us/step - loss: 163.0632 - acc: 0.6525
Epoch 10/1000
118/118 [==============================] - 0s 680us/step - loss: 80.5851 - ac

Epoch 81/1000
118/118 [==============================] - 0s 593us/step - loss: 56.6423 - acc: 0.9068
Epoch 82/1000
118/118 [==============================] - 0s 458us/step - loss: 79.3332 - acc: 0.8220
Epoch 83/1000
118/118 [==============================] - 0s 576us/step - loss: 82.5100 - acc: 0.8305
Epoch 84/1000
118/118 [==============================] - 0s 572us/step - loss: 110.7206 - acc: 0.7373
Epoch 85/1000
118/118 [==============================] - 0s 607us/step - loss: 116.2737 - acc: 0.7712
Epoch 86/1000
118/118 [==============================] - 0s 635us/step - loss: 73.6003 - acc: 0.8644
Epoch 87/1000
118/118 [==============================] - 0s 639us/step - loss: 90.6712 - acc: 0.7712
Epoch 88/1000
118/118 [==============================] - 0s 625us/step - loss: 100.8607 - acc: 0.7627
Epoch 89/1000
118/118 [==============================] - 0s 566us/step - loss: 35.2885 - acc: 0.8814
Epoch 90/1000
118/118 [==============================] - 0s 599us/step - loss: 21.8370 -

118/118 [==============================] - 0s 535us/step - loss: 61.0361 - acc: 0.8305
Epoch 162/1000
118/118 [==============================] - 0s 546us/step - loss: 47.5023 - acc: 0.8814
Epoch 163/1000
118/118 [==============================] - 0s 600us/step - loss: 68.4621 - acc: 0.8390
Epoch 164/1000
118/118 [==============================] - 0s 842us/step - loss: 85.1470 - acc: 0.8475
Epoch 165/1000
118/118 [==============================] - 0s 827us/step - loss: 69.5143 - acc: 0.8220
Epoch 166/1000
118/118 [==============================] - 0s 628us/step - loss: 61.9329 - acc: 0.8729
Epoch 167/1000
118/118 [==============================] - 0s 593us/step - loss: 82.3021 - acc: 0.8136
Epoch 168/1000
118/118 [==============================] - 0s 547us/step - loss: 63.6295 - acc: 0.8644
Epoch 169/1000
118/118 [==============================] - 0s 555us/step - loss: 30.5622 - acc: 0.9153
Epoch 170/1000
118/118 [==============================] - 0s 591us/step - loss: 63.1094 - acc: 0.

118/118 [==============================] - 0s 678us/step - loss: 17.8528 - acc: 0.9661
Epoch 321/1000
118/118 [==============================] - 0s 745us/step - loss: 51.4037 - acc: 0.8814
Epoch 322/1000
118/118 [==============================] - 0s 712us/step - loss: 51.4922 - acc: 0.8898
Epoch 323/1000
118/118 [==============================] - 0s 610us/step - loss: 14.6589 - acc: 0.9661
Epoch 324/1000
118/118 [==============================] - 0s 551us/step - loss: 67.5446 - acc: 0.8136
Epoch 325/1000
118/118 [==============================] - 0s 642us/step - loss: 42.4618 - acc: 0.8559
Epoch 326/1000
118/118 [==============================] - 0s 958us/step - loss: 44.0123 - acc: 0.9068
Epoch 327/1000
118/118 [==============================] - 0s 729us/step - loss: 62.1806 - acc: 0.8559
Epoch 328/1000
118/118 [==============================] - 0s 619us/step - loss: 60.3187 - acc: 0.8390
Epoch 329/1000
118/118 [==============================] - 0s 628us/step - loss: 25.4446 - acc: 0.

118/118 [==============================] - 0s 592us/step - loss: 25.0269 - acc: 0.9068
Epoch 481/1000
118/118 [==============================] - ETA: 0s - loss: 0.0000e+00 - acc: 1.000 - 0s 765us/step - loss: 5.0030 - acc: 0.9831
Epoch 482/1000
118/118 [==============================] - 0s 831us/step - loss: 4.8072 - acc: 0.9831
Epoch 483/1000
118/118 [==============================] - 0s 847us/step - loss: 28.1650 - acc: 0.8983
Epoch 484/1000
118/118 [==============================] - 0s 644us/step - loss: 22.4223 - acc: 0.9661
Epoch 485/1000
118/118 [==============================] - 0s 643us/step - loss: 11.5597 - acc: 0.9576
Epoch 486/1000
118/118 [==============================] - 0s 580us/step - loss: 51.3181 - acc: 0.8814
Epoch 487/1000
118/118 [==============================] - 0s 592us/step - loss: 13.0552 - acc: 0.9576
Epoch 488/1000
118/118 [==============================] - 0s 627us/step - loss: 38.4590 - acc: 0.9153
Epoch 489/1000
118/118 [==============================] -

118/118 [==============================] - 0s 720us/step - loss: 11.3716 - acc: 0.9576
Epoch 560/1000
118/118 [==============================] - 0s 678us/step - loss: 5.0528 - acc: 0.9831
Epoch 561/1000
118/118 [==============================] - ETA: 0s - loss: 2.4660 - acc: 0.9773    - 0s 593us/step - loss: 4.4235 - acc: 0.9746
Epoch 562/1000
118/118 [==============================] - 0s 642us/step - loss: 46.2376 - acc: 0.9237
Epoch 563/1000
118/118 [==============================] - 0s 653us/step - loss: 34.1847 - acc: 0.9322
Epoch 564/1000
118/118 [==============================] - 0s 573us/step - loss: 14.5035 - acc: 0.9661
Epoch 565/1000
118/118 [==============================] - 0s 595us/step - loss: 50.0274 - acc: 0.8814
Epoch 566/1000
118/118 [==============================] - 0s 585us/step - loss: 26.1287 - acc: 0.9322
Epoch 567/1000
118/118 [==============================] - 0s 599us/step - loss: 22.6927 - acc: 0.9237
Epoch 568/1000
118/118 [==============================] -

118/118 [==============================] - 0s 720us/step - loss: 27.7427 - acc: 0.9237
Epoch 718/1000
118/118 [==============================] - 0s 647us/step - loss: 21.7734 - acc: 0.9407
Epoch 719/1000
118/118 [==============================] - 0s 585us/step - loss: 5.2544 - acc: 0.9831
Epoch 720/1000
118/118 [==============================] - 0s 595us/step - loss: 5.6438 - acc: 0.9661
Epoch 721/1000
118/118 [==============================] - 0s 610us/step - loss: 15.8667 - acc: 0.9407
Epoch 722/1000
118/118 [==============================] - 0s 553us/step - loss: 24.1046 - acc: 0.9237
Epoch 723/1000
118/118 [==============================] - 0s 639us/step - loss: 26.5289 - acc: 0.9322
Epoch 724/1000
118/118 [==============================] - 0s 565us/step - loss: 20.4494 - acc: 0.9492
Epoch 725/1000
118/118 [==============================] - 0s 601us/step - loss: 7.8335 - acc: 0.9661
Epoch 726/1000
118/118 [==============================] - 0s 565us/step - loss: 6.4442 - acc: 0.9576

118/118 [==============================] - 0s 644us/step - loss: 25.5028 - acc: 0.9237
Epoch 878/1000
118/118 [==============================] - 0s 703us/step - loss: 5.7972 - acc: 0.9661
Epoch 879/1000
118/118 [==============================] - 0s 661us/step - loss: 37.3837 - acc: 0.9068
Epoch 880/1000
118/118 [==============================] - 0s 588us/step - loss: 18.0737 - acc: 0.9492
Epoch 881/1000
118/118 [==============================] - 0s 600us/step - loss: 12.4058 - acc: 0.9661
Epoch 882/1000
118/118 [==============================] - 0s 678us/step - loss: 6.7164 - acc: 0.9661
Epoch 883/1000
118/118 [==============================] - 0s 661us/step - loss: 22.6286 - acc: 0.9576
Epoch 884/1000
118/118 [==============================] - 0s 568us/step - loss: 24.9885 - acc: 0.9322
Epoch 885/1000
118/118 [==============================] - 0s 584us/step - loss: 17.7491 - acc: 0.9492
Epoch 886/1000
118/118 [==============================] - 0s 653us/step - loss: 14.4912 - acc: 0.94

In [7]:
# test
Xtest_loss, Xtest_acc = model.evaluate(wine_pca_test,y_test)
print(Xtest_acc)

2/2 [==============================] - 0s 1ms/step - loss: 20.3926 - acc: 0.9000
0.8999999761581421


In [8]:
# 예측
Ttest = model.predict(wine_pca_test)
                
print(Ttest) 


[[0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.0000000e+00 1.7193523e-35 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [0.000000

In [15]:
# 행 중에 가장 큰 애를 가져온다.
# 이를 y_test와 비교하면 된다!
np.argmax(Ttest, axis = 1)

array([1, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2,
       1, 0, 1, 2, 1, 0, 2, 1, 1, 2, 0, 2, 1, 1, 2, 2, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 2, 2, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 2], dtype=int64)

In [10]:
y_test

array([1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0, 2, 0, 0, 1, 2, 2, 1, 0, 1, 0, 2,
       1, 1, 1, 2, 1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 2, 2])