In [1]:
from tensorflow.keras import models, layers
from sklearn.model_selection import train_test_split
import numpy as np


In [2]:
# wine
# mulit, output : 0, 1, 2
from sklearn.datasets import load_wine

data_wine = load_wine();
X = data_wine.data
y = data_wine.target

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=1/3)

In [4]:
print(data_wine.feature_names)
print(data_wine.target_names)
print(data_wine.DESCR)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    =========================

In [5]:
import pandas as pd
df = pd.DataFrame(X, columns = data_wine.feature_names)
df["target"] = y

# units의 수
print(len(df["target"].unique()))

# input_shape의 수
print(len(data_wine.feature_names))

df

3
13


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [3]:
# softmax

model = models.Sequential()

model.add(layers.Dense(units = 256, activation="relu", input_shape=(13,)))
#model.add(layers.Dropout(0.5)) # 드롭아웃 : 오버피팅 막는법
model.add(layers.Dense(units = 128, activation="relu"))

model.add(layers.Dense(units = 64, activation="relu"))

model.add(layers.Dense(units = 3, activation="softmax"))

model.compile(optimizer="adam",
             loss = "sparse_categorical_crossentropy",
             metrics = ["acc"])

model.fit(X_train,y_train,epochs = 1000, batch_size = 1, verbose = 1)

Epoch 1/1000
118/118 [==============================] - 0s 934us/step - loss: 10.2466 - acc: 0.5000
Epoch 2/1000
118/118 [==============================] - 0s 923us/step - loss: 6.0686 - acc: 0.5000
Epoch 3/1000
118/118 [==============================] - 0s 827us/step - loss: 2.8257 - acc: 0.5678
Epoch 4/1000
118/118 [==============================] - 0s 922us/step - loss: 1.4494 - acc: 0.6271
Epoch 5/1000
118/118 [==============================] - 0s 915us/step - loss: 2.0416 - acc: 0.5339
Epoch 6/1000
118/118 [==============================] - 0s 924us/step - loss: 1.4072 - acc: 0.5763
Epoch 7/1000
118/118 [==============================] - 0s 890us/step - loss: 1.1855 - acc: 0.7203
Epoch 8/1000
118/118 [==============================] - 0s 856us/step - loss: 1.0407 - acc: 0.6695
Epoch 9/1000
118/118 [==============================] - 0s 856us/step - loss: 1.1766 - acc: 0.6610
Epoch 10/1000
118/118 [==============================] - 0s 1ms/step - loss: 0.9500 - acc: 0.6695
Epoch 11/1

118/118 [==============================] - 0s 813us/step - loss: 0.1789 - acc: 0.9407
Epoch 83/1000
118/118 [==============================] - 0s 721us/step - loss: 0.1663 - acc: 0.9237
Epoch 84/1000
118/118 [==============================] - 0s 729us/step - loss: 0.1657 - acc: 0.9407
Epoch 85/1000
118/118 [==============================] - 0s 763us/step - loss: 0.3781 - acc: 0.8898
Epoch 86/1000
118/118 [==============================] - 0s 771us/step - loss: 0.2334 - acc: 0.8983
Epoch 87/1000
118/118 [==============================] - 0s 678us/step - loss: 0.1534 - acc: 0.9576
Epoch 88/1000
118/118 [==============================] - 0s 746us/step - loss: 0.2275 - acc: 0.8898
Epoch 89/1000
118/118 [==============================] - 0s 746us/step - loss: 0.1299 - acc: 0.9322
Epoch 90/1000
118/118 [==============================] - 0s 788us/step - loss: 0.2327 - acc: 0.9153
Epoch 91/1000
118/118 [==============================] - 0s 788us/step - loss: 0.1412 - acc: 0.9492
Epoch 92/1000


118/118 [==============================] - 0s 751us/step - loss: 0.0847 - acc: 0.9576
Epoch 164/1000
118/118 [==============================] - 0s 796us/step - loss: 0.4473 - acc: 0.8983
Epoch 165/1000
118/118 [==============================] - 0s 789us/step - loss: 0.2381 - acc: 0.8983
Epoch 166/1000
118/118 [==============================] - 0s 763us/step - loss: 0.1977 - acc: 0.9237
Epoch 167/1000
118/118 [==============================] - 0s 834us/step - loss: 0.1262 - acc: 0.9407
Epoch 168/1000
118/118 [==============================] - 0s 983us/step - loss: 0.0928 - acc: 0.9492
Epoch 169/1000
118/118 [==============================] - 0s 793us/step - loss: 0.4175 - acc: 0.8729
Epoch 170/1000
118/118 [==============================] - 0s 776us/step - loss: 0.1333 - acc: 0.9322
Epoch 171/1000
118/118 [==============================] - 0s 915us/step - loss: 0.1933 - acc: 0.9492
Epoch 172/1000
118/118 [==============================] - 0s 932us/step - loss: 0.1453 - acc: 0.9322
Epoch

Epoch 242/1000
118/118 [==============================] - 0s 754us/step - loss: 0.1130 - acc: 0.9576
Epoch 243/1000
118/118 [==============================] - 0s 746us/step - loss: 0.1229 - acc: 0.9407
Epoch 244/1000
118/118 [==============================] - 0s 797us/step - loss: 0.0582 - acc: 0.9746
Epoch 245/1000
118/118 [==============================] - 0s 729us/step - loss: 0.0803 - acc: 0.9576
Epoch 246/1000
118/118 [==============================] - 0s 703us/step - loss: 0.2127 - acc: 0.9407
Epoch 247/1000
118/118 [==============================] - 0s 729us/step - loss: 0.2834 - acc: 0.9068
Epoch 248/1000
118/118 [==============================] - 0s 780us/step - loss: 0.1134 - acc: 0.9661
Epoch 249/1000
118/118 [==============================] - 0s 729us/step - loss: 0.0990 - acc: 0.9492
Epoch 250/1000
118/118 [==============================] - 0s 822us/step - loss: 0.1117 - acc: 0.9407
Epoch 251/1000
118/118 [==============================] - 0s 754us/step - loss: 0.1156 - ac

118/118 [==============================] - 0s 819us/step - loss: 0.0487 - acc: 0.9746
Epoch 403/1000
118/118 [==============================] - 0s 778us/step - loss: 0.0520 - acc: 0.9746
Epoch 404/1000
118/118 [==============================] - 0s 983us/step - loss: 0.0529 - acc: 0.9831
Epoch 405/1000
118/118 [==============================] - 0s 924us/step - loss: 0.0577 - acc: 0.9831
Epoch 406/1000
118/118 [==============================] - 0s 924us/step - loss: 0.0581 - acc: 0.9661
Epoch 407/1000
118/118 [==============================] - 0s 729us/step - loss: 0.2304 - acc: 0.9407
Epoch 408/1000
118/118 [==============================] - 0s 745us/step - loss: 0.1571 - acc: 0.9407
Epoch 409/1000
118/118 [==============================] - 0s 768us/step - loss: 0.0408 - acc: 0.9915
Epoch 410/1000
118/118 [==============================] - 0s 743us/step - loss: 0.1584 - acc: 0.9407
Epoch 411/1000
118/118 [==============================] - 0s 751us/step - loss: 0.1143 - acc: 0.9661
Epoch

118/118 [==============================] - 0s 1ms/step - loss: 0.0665 - acc: 0.9746
Epoch 563/1000
118/118 [==============================] - 0s 763us/step - loss: 0.0479 - acc: 0.9661
Epoch 564/1000
118/118 [==============================] - 0s 686us/step - loss: 0.0563 - acc: 0.9746
Epoch 565/1000
118/118 [==============================] - 0s 695us/step - loss: 0.0435 - acc: 0.9831
Epoch 566/1000
118/118 [==============================] - 0s 720us/step - loss: 0.0859 - acc: 0.9661
Epoch 567/1000
118/118 [==============================] - 0s 695us/step - loss: 0.1041 - acc: 0.9576
Epoch 568/1000
118/118 [==============================] - 0s 754us/step - loss: 0.0417 - acc: 0.9831
Epoch 569/1000
118/118 [==============================] - 0s 873us/step - loss: 0.0406 - acc: 0.9661
Epoch 570/1000
118/118 [==============================] - 0s 780us/step - loss: 0.0338 - acc: 0.9831
Epoch 571/1000
118/118 [==============================] - 0s 746us/step - loss: 0.0323 - acc: 0.9831
Epoch 5

118/118 [==============================] - 0s 788us/step - loss: 0.2190 - acc: 0.9576
Epoch 724/1000
118/118 [==============================] - 0s 678us/step - loss: 0.2257 - acc: 0.9407
Epoch 725/1000
118/118 [==============================] - 0s 941us/step - loss: 0.0524 - acc: 0.9746
Epoch 726/1000
118/118 [==============================] - 0s 669us/step - loss: 0.0630 - acc: 0.9746
Epoch 727/1000
118/118 [==============================] - 0s 703us/step - loss: 0.0554 - acc: 0.9746
Epoch 728/1000
118/118 [==============================] - 0s 737us/step - loss: 0.0527 - acc: 0.9746
Epoch 729/1000
118/118 [==============================] - 0s 703us/step - loss: 0.0327 - acc: 0.9915
Epoch 730/1000
118/118 [==============================] - 0s 669us/step - loss: 0.0200 - acc: 0.9915
Epoch 731/1000
118/118 [==============================] - 0s 754us/step - loss: 0.0113 - acc: 0.9915
Epoch 732/1000
118/118 [==============================] - 0s 678us/step - loss: 0.0319 - acc: 0.9915
Epoch

118/118 [==============================] - 0s 746us/step - loss: 0.0166 - acc: 1.0000
Epoch 886/1000
118/118 [==============================] - 0s 703us/step - loss: 0.0215 - acc: 0.9915
Epoch 887/1000
118/118 [==============================] - 0s 780us/step - loss: 0.1813 - acc: 0.9492
Epoch 888/1000
118/118 [==============================] - 0s 771us/step - loss: 0.0690 - acc: 0.9576
Epoch 889/1000
118/118 [==============================] - 0s 678us/step - loss: 0.0241 - acc: 0.9831
Epoch 890/1000
118/118 [==============================] - 0s 686us/step - loss: 0.2796 - acc: 0.9492
Epoch 891/1000
118/118 [==============================] - 0s 830us/step - loss: 0.0265 - acc: 0.9915
Epoch 892/1000
118/118 [==============================] - 0s 686us/step - loss: 0.0141 - acc: 1.0000
Epoch 893/1000
118/118 [==============================] - 0s 703us/step - loss: 0.0153 - acc: 1.0000
Epoch 894/1000
118/118 [==============================] - 0s 737us/step - loss: 0.0578 - acc: 0.9831
Epoch

In [4]:
# Test 하는 법

XTest_loss, XTest_acc = model.evaluate(X_test, y_test) # 원래 test 데이터가 들어가야 된다.

print(XTest_acc)

2/2 [==============================] - 0s 1ms/step - loss: 0.2771 - acc: 0.9500
0.949999988079071


In [8]:
Ttest = model.predict(X_test)
                
print(Ttest)

[[9.12911902e-27 1.00000000e+00 3.30186846e-30]
 [6.46235705e-08 1.24946091e-04 9.99874949e-01]
 [9.99999881e-01 7.89973598e-08 3.76195048e-19]
 [1.00000000e+00 1.00873226e-10 1.00755405e-24]
 [3.21180504e-09 1.00000000e+00 6.59595127e-14]
 [1.20882149e-26 1.00000000e+00 8.42265197e-29]
 [3.50141330e-14 1.25647201e-11 1.00000000e+00]
 [1.32299170e-01 8.63970101e-01 3.73077043e-03]
 [1.17994140e-18 1.00000000e+00 2.29527524e-22]
 [4.49067684e-36 1.00000000e+00 0.00000000e+00]
 [9.89257720e-18 1.00000000e+00 5.85940819e-20]
 [4.45600450e-01 5.54129660e-01 2.69885495e-04]
 [4.29160863e-01 5.70707977e-01 1.31150635e-04]
 [1.10679365e-11 8.59654348e-10 1.00000000e+00]
 [1.73107419e-34 1.00000000e+00 1.08188986e-36]
 [2.99591105e-02 9.52000976e-01 1.80399232e-02]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.95124823e-08 2.69479096e-06 9.99997258e-01]
 [5.43703132e-38 1.00000000e+00 4.77984251e-37]
 [3.57047829e-04 9.99640822e-01 2.111872

In [9]:
# 행 중에 가장 큰 애를 가져온다.
# 이를 y_test와 비교하면 된다!
np.argmax(Ttest, axis = 1)

array([1, 2, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 0, 0, 1, 2, 2, 1, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 0, 1, 1, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0, 1, 2], dtype=int64)

In [10]:
y_test

array([1, 2, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 0, 1, 2, 2, 1, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 0, 1, 1, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0, 1, 1])